source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'SocraticaPlus' do

  use_frameworks!

  pod 'ZVProgressHUD', :git => 'https://github.com/zevwings/ZVProgressHUD.git'

end
