# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SocraticaPlus' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'ZVProgressHUD', :git => 'https://github.com/zevwings/ZVProgressHUD.git'
pod 'NKVPhonePicker'

end
